security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        Usuarios:
            entity:
                class: App\Entity\Usuario
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: Usuarios  # <--- Cambiado para coincidir con el provider definido arriba

            entry_point: App\Security\LoginAuthenticator # Aquí le dices a Symfony qué autenticador usar

            # Opciones de autenticación (añadir según sea necesario)
            form_login: 
                login_path: app_login
                check_path: app_login
                default_target_path: /home  # Redirigir después del login

            logout:
                path: app_logout
                target: /login
            custom_authenticator: App\Security\LoginAuthenticator

            # switch_user: true  # Para cambiar de usuario en el sistema

    # Control de acceso a rutas
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/manager, roles: ROLE_MANAGER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
