security:
    # ...
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Proveedor actualizado para la nueva entidad 'User'
    providers:
        app_user_provider:  # Cambié el nombre a 'app_user_provider' para que coincida con la convención de nombres
            entity:
                class: App\Entity\User  # Cambié 'Usuario' por 'User'
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/ 
            security: false

        main:
            lazy: true
            provider: app_user_provider  # Cambié 'Usuarios' a 'app_user_provider' 
            entry_point: App\Security\LoginAuthenticator 

            form_login: 
                login_path: app_login
                check_path: app_login
                default_target_path: /home

            logout:
                path: app_logout
                target: /login
            custom_authenticator: App\Security\LoginAuthenticator

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/manager, roles: ROLE_MANAGER }


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
