security:
    # ...
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto' #como se encripta

    # Proveedor actualizado para la nueva entidad 'User'
    providers:
        app_user_provider:  # Cambié el nombre a 'app_user_provider' para que coincida con la convención de nombres
            entity:
                class: App\Entity\User  # Cambié 'Usuario' por 'User'
                property: email #campo identificador de user

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/ 
            security: false

        main:
            lazy: true
            provider: app_user_provider  # Cambié 'Usuarios' a 'app_user_provider' 
            entry_point: App\Security\LoginAuthenticator #Usa la clase LoginAuthenticator para manejar la autenticación.
            access_denied_handler: App\Security\AccessDeniedHandler # Si un usuario no tiene permiso, maneja la respuesta con esta clase.


            form_login: 
                login_path: app_login # Define la ruta donde está el formulario de login (/login). #securityController
                check_path: app_login
                default_target_path: /home

            logout:
                path: app_logout #securityController
                target: /login
            custom_authenticator: App\Security\LoginAuthenticator   #AUTHENTICATOR  ------------------

    access_control:

        #- { path: ^/home, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/Manager, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }
        # Rutas para ADMIN (solo ROLE_ADMIN)
           # Rutas para ADMIN (solo ROLE_ADMIN)
        - { path: ^/admin, roles: ROLE_ADMIN }

    # Rutas para USER (solo ROLE_USER)
        #- { path: ^/home, roles: ROLE_USER }

    # Rutas para MANAGER (solo ROLE_MANAGER)
        - { path: ^/Manager, roles: ROLE_MANAGER }



when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon