<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Playlist extends \App\Entity\Playlist implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Likes' => [parent::class, 'Likes', null],
        "\0".parent::class."\0".'Name' => [parent::class, 'Name', null],
        "\0".parent::class."\0".'Owner' => [parent::class, 'Owner', null],
        "\0".parent::class."\0".'Replays' => [parent::class, 'Replays', null],
        "\0".parent::class."\0".'Visibility' => [parent::class, 'Visibility', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'playlistSongs' => [parent::class, 'playlistSongs', null],
        "\0".parent::class."\0".'userPlaylists' => [parent::class, 'userPlaylists', null],
        'Likes' => [parent::class, 'Likes', null],
        'Name' => [parent::class, 'Name', null],
        'Owner' => [parent::class, 'Owner', null],
        'Replays' => [parent::class, 'Replays', null],
        'Visibility' => [parent::class, 'Visibility', null],
        'id' => [parent::class, 'id', null],
        'playlistSongs' => [parent::class, 'playlistSongs', null],
        'userPlaylists' => [parent::class, 'userPlaylists', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
