<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Song extends \App\Entity\Song implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Author' => [parent::class, 'Author', null],
        "\0".parent::class."\0".'Duration' => [parent::class, 'Duration', null],
        "\0".parent::class."\0".'File' => [parent::class, 'File', null],
        "\0".parent::class."\0".'Genre' => [parent::class, 'Genre', null],
        "\0".parent::class."\0".'Likes' => [parent::class, 'Likes', null],
        "\0".parent::class."\0".'Replays' => [parent::class, 'Replays', null],
        "\0".parent::class."\0".'Title' => [parent::class, 'Title', null],
        "\0".parent::class."\0".'album' => [parent::class, 'album', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'playlistSongs' => [parent::class, 'playlistSongs', null],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null],
        'Author' => [parent::class, 'Author', null],
        'Duration' => [parent::class, 'Duration', null],
        'File' => [parent::class, 'File', null],
        'Genre' => [parent::class, 'Genre', null],
        'Likes' => [parent::class, 'Likes', null],
        'Replays' => [parent::class, 'Replays', null],
        'Title' => [parent::class, 'Title', null],
        'album' => [parent::class, 'album', null],
        'id' => [parent::class, 'id', null],
        'playlistSongs' => [parent::class, 'playlistSongs', null],
        'users' => [parent::class, 'users', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
