<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Birth_date' => [parent::class, 'Birth_date', null],
        "\0".parent::class."\0".'Email' => [parent::class, 'Email', null],
        "\0".parent::class."\0".'Name' => [parent::class, 'Name', null],
        "\0".parent::class."\0".'Password' => [parent::class, 'Password', null],
        "\0".parent::class."\0".'Profile' => [parent::class, 'Profile', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'playlists' => [parent::class, 'playlists', null],
        "\0".parent::class."\0".'songs' => [parent::class, 'songs', null],
        "\0".parent::class."\0".'userPlaylists' => [parent::class, 'userPlaylists', null],
        'Birth_date' => [parent::class, 'Birth_date', null],
        'Email' => [parent::class, 'Email', null],
        'Name' => [parent::class, 'Name', null],
        'Password' => [parent::class, 'Password', null],
        'Profile' => [parent::class, 'Profile', null],
        'id' => [parent::class, 'id', null],
        'playlists' => [parent::class, 'playlists', null],
        'songs' => [parent::class, 'songs', null],
        'userPlaylists' => [parent::class, 'userPlaylists', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
