<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXHb2AzL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXHb2AzL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXHb2AzL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXHb2AzL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXHb2AzL\App_KernelDevDebugContainer([
    'container.build_hash' => 'XHb2AzL',
    'container.build_id' => '027d5e6b',
    'container.build_time' => 1739026152,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXHb2AzL');
