<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLjTwHWA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLjTwHWA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLjTwHWA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLjTwHWA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLjTwHWA\App_KernelDevDebugContainer([
    'container.build_hash' => 'LjTwHWA',
    'container.build_id' => '3fd22da8',
    'container.build_time' => 1738837349,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLjTwHWA');
