<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGaXqUhg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGaXqUhg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGaXqUhg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGaXqUhg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGaXqUhg\App_KernelDevDebugContainer([
    'container.build_hash' => 'GaXqUhg',
    'container.build_id' => '6b729f33',
    'container.build_time' => 1738754132,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGaXqUhg');
