<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'app_playlist' => [[], ['_controller' => 'App\\Controller\\PlaylistController::index'], [], [['text', '/playlist/new']], [], [], []],
    'app_playlist_song_new' => [[], ['_controller' => 'App\\Controller\\PlaylistSongController::createPlaylistWithSong'], [], [['text', '/playlist-song/new']], [], [], []],
    'app_profile' => [[], ['_controller' => 'App\\Controller\\ProfileController::index'], [], [['text', '/profile/new']], [], [], []],
    'app_song' => [[], ['_controller' => 'App\\Controller\\SongController::index'], [], [['text', '/song/new']], [], [], []],
    'app_style' => [[], ['_controller' => 'App\\Controller\\StyleController::index'], [], [['text', '/style/new']], [], [], []],
    'app_user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/new']], [], [], []],
    'app_user_playlist' => [[], ['_controller' => 'App\\Controller\\UserPlaylistController::index'], [], [['text', '/user/playlist/new']], [], [], []],
    'App\Controller\Admin\DashboardController::index' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'App\Controller\PlaylistController::index' => [[], ['_controller' => 'App\\Controller\\PlaylistController::index'], [], [['text', '/playlist/new']], [], [], []],
    'App\Controller\PlaylistSongController::createPlaylistWithSong' => [[], ['_controller' => 'App\\Controller\\PlaylistSongController::createPlaylistWithSong'], [], [['text', '/playlist-song/new']], [], [], []],
    'App\Controller\ProfileController::index' => [[], ['_controller' => 'App\\Controller\\ProfileController::index'], [], [['text', '/profile/new']], [], [], []],
    'App\Controller\SongController::index' => [[], ['_controller' => 'App\\Controller\\SongController::index'], [], [['text', '/song/new']], [], [], []],
    'App\Controller\StyleController::index' => [[], ['_controller' => 'App\\Controller\\StyleController::index'], [], [['text', '/style/new']], [], [], []],
    'App\Controller\UserController::index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/new']], [], [], []],
    'App\Controller\UserPlaylistController::index' => [[], ['_controller' => 'App\\Controller\\UserPlaylistController::index'], [], [['text', '/user/playlist/new']], [], [], []],
];
